# This is a basic workflow to help you get started with Actions

name: CI

on:
  create:

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo Hello, world!

  
