# This is a basic workflow to help you get started with Actions

name: RELEASE


on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Package
      - uses: actions/checkout@master
      - name: Setup Node environment
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
        name: Publish to NPM
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  
