# This is a basic workflow to help you get started with Actions

name: RELEASE

on:
  release:
    types: [published]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'RELEASED'
  
