# This is a basic workflow to help you get started with Actions

name: TEST

on:
  release:
    types: [published]

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - run: echo 'RELEASED'
  
