# This is a basic workflow to help you get started with Actions

name: TEST

on:
  create

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo 'This was a change to a ${{github.ref_type}} - ${{github.ref}}'

  
