# This is a basic workflow to help you get started with Actions

name: TEST

on:
  create:
  delete:

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo 'Event - ${{github.event_name}} - REF - ${{github.ref}}'

  
