# This is a basic workflow to help you get started with Actions

name: TEST

on:
  push:
    tags: 'v*' 

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: 'Get Previous tag'
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@0.2.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - run: echo '${{ steps.previoustag.outputs.tag }}'
      - run: echo process.env

  
